### ISSUE TITLE
smote_multiclass error : dataframe has no attribute 'Status'

### ISSUE THREAD

**Issue by nadiaenh** [cpappas18/Dysarthria-Classifier#11]
This is happening because the multi-class datasets (like _all_disorders_remove_std_onehot.csv_) don't have a 'Status' column but rather 4 columns (Control, PD, etc.)

**Comment by cpappas18** [comment]
Did you set the argument one_hot_encoded = True?

**Comment by nadiaenh** [comment]
Solved :)
